---
title: "flat_majuscule.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Majuscule

```{r function-majuscule}
#' majuscule Title
#'
#' @param x Une chaine de caractères
#'
#' @return Une chaine de caractèreq avec une majuscule
#' @export
#'
#' @examples
majuscule <- function(x){
  paste0(toupper(substr(x, 1, 1)), substr(x, 2, nchar(x)))
} 
```

```{r examples-majuscule}
majuscule("mon petit chat")
majuscule("ATTENTION DERRIERE TOI !")
```

```{r tests-majuscule}
test_that("majuscule works", {
  expect_equal(majuscule("mon petit chat"),"Mon petit chat")
})
test_that("majuscule works", {
  expect_equal(majuscule("ATTENTION DERRIERE TOI !"),"ATTENTION DERRIERE TOI !")
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_majuscule.Rmd", vignette_name = "Majuscule")
```

