# WARNING - Generated by {fusen} from dev/flat_extract_part.Rmd: do not edit by hand

Coucou<-"Amendement n°3"
test_that("extract_part works", {
  expect_equal(extract_part(x=Coucou,sep="°",partie=2),expected = "3")
  expect_error(extract_part(x=1:10,sep="w",partie=3))
})
