# WARNING - Generated by {fusen} from /dev/flat_nuancier.Rmd: do not edit by hand

test_that("nuancier works", {
  expect_equal(nuancier("white","#CC2828",5),c("#FFFFFF","#F2C9C9","#E59393", "#D85D5D","#CC2828"))
})
test_that("nuancier bugs", {
  expect_error(nuancier(1,"a",5),"in")
})
