# WARNING - Generated by {fusen} from /dev/flat_majuscule.Rmd: do not edit by hand

test_that("majuscule works", {
  expect_equal(majuscule("mon petit chat"),"Mon petit chat")
})
test_that("majuscule works", {
  expect_equal(majuscule("ATTENTION DERRIERE TOI !"),"ATTENTION DERRIERE TOI !")
})
