# WARNING - Generated by {fusen} from dev/flat_extract_part.Rmd: do not edit by hand

#' extract_part Title
#'
#' @param x Une chaine de caractères
#' @param sep Une chaine de caractères séparant deux parties
#' @param partie Un chiffre indiquant quelle partie on veut récupérer
#' @return Une chaine de caractères
#'
#' @export
#'
#' @examples
#' Coucou<-"Amendement n°3"
#' extract_part(x=Coucou,sep="°",partie=2)
extract_part <- function(x,sep,partie){
  sapply(strsplit(x,sep), `[`, partie)
} 

