# WARNING - Generated by {fusen} from /dev/flat_majuscule.Rmd: do not edit by hand

#' majuscule Title
#'
#' @param x Une chaine de caractÃ¨res
#'
#' @return Une chaine de caractÃ¨req avec une majuscule
#' @export
#'
#' @examples
#' majuscule("mon petit chat")
#' majuscule("ATTENTION DERRIERE TOI !")
majuscule <- function(x){
  paste0(toupper(substr(x, 1, 1)), substr(x, 2, nchar(x)))
} 
