# WARNING - Generated by {fusen} from /dev/flat_nuancier.Rmd: do not edit by hand

#' nuancier Title
#'
#' @param couldep Couleur de dÃ©part du dÃ©gradÃ©
#' @param coularr Couleur d'arrivÃ©e du dÃ©gradÃ©
#' @param nombre Nombre de couleurs entre les deux
#' @importFrom grDevices colorRampPalette
#' @return un vecteur contenant une liste de couleurs
#' @export
#'
#' @examples
#' nuancier("white","#CC2828",5)
nuancier <- function(couldep,coularr,nombre){
  CreeMoiUnGradient <- colorRampPalette(c(couldep, coularr))
  CreeMoiUnGradient(nombre)
}
