# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' sortunjpeg sortunjpeg
#'
#' @param graph L'objet Ã  afficher dans le jpeg
#' @param largeur La largeur en pixels
#' @param hauteur La hauteur en pixels
#' @param titre Le nom du jpeg qui sera exportÃ©, sans l'extension
#' @return un fichier contenant l'objet appelÃ© image
#'
#' @importFrom grDevices jpeg
#' @importFrom grDevices dev.off
#' @export
#'
#' @examples
#' library(dplyr)
#' library(ggplot2)
#' sampledata<-data.frame(x=1:10,y=1:10)
#' graphique<-ggplot(sampledata)+
#'   geom_point(aes(x,y))
#' \dontrun{
#' sortunjpeg(graphique,200,200,"graphiquedetest")
#' }
#' 
sortunjpeg<-function(graph,largeur,hauteur,titre){
  jpeg(filename = paste0(titre,".jpg"), width=largeur, height = hauteur, quality=100, units = "px",type="cairo")
  plot(graph)
  dev.off()
}
