# WARNING - Generated by {fusen} from /dev/flat_sortunsvg.Rmd: do not edit by hand

#' sortunsvg sortunsvg
#'
#' @param graph L'objet Ã  afficher dans le svg
#' @param largeur La largeur en points
#' @param hauteur La hauteur en points
#' @param titre Le nom du svg qui sera exportÃ©, sans l'extension
#' @return un fichier contenant l'objet appelÃ© image
#'
#' @importFrom svglite svglite
#' @importFrom grDevices dev.off
#' @export
#'
#' @examples
#' library(dplyr)
#' library(ggplot2)
#' sampledata<-data.frame(x=1:10,y=1:10)
#' graphique2<-ggplot(sampledata)+
#'   geom_point(aes(x,y))
#' \dontrun{
#' sortunsvg(graphique2,2,2,"graphiquedetest")
#' }
sortunsvg<-function(graph,largeur,hauteur,titre){
  svglite(filename = paste0(titre,".svg"), width=largeur, height = hauteur, standalone=TRUE)
  plot(graph)
  dev.off()
}
