# WARNING - Generated by {fusen} from dev/flat_minimal.Rmd: do not edit by hand

#' sortunjpeg sortunjpeg
#'
#' @param graph L'objet à afficher dans le jpeg
#' @param largeur La largeur en pixels
#' @param hauteur La hauteur en pixels
#' @param titre Le nom du jpeg qui sera exporté, sans l'extension
#' @return un fichier contenant l'objet appelé image
#'
#' @importFrom ragg agg_jpeg
#' @importFrom grDevices dev.off
#' @export
#'
#' @examples
#' library(dplyr)
#' library(ggplot2)
#' sampledata<-data.frame(x=1:10,y=1:10)
#' graphique<-ggplot(sampledata)+
#'   geom_point(aes(x,y))
#' \dontrun{
#' sortunjpeg(graphique,200,200,"graphiquedetest")
#' }
#'
sortunjpeg<-function(graph,largeur,hauteur,titre){
  ragg::agg_jpeg(filename = paste0(titre,".jpg"), width=largeur, height = hauteur)
  plot(graph)
  dev.off()
}
